trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: HELLO_WORLD
    value: "default_value"

jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
      - script: |
          echo Building the project...
          echo "The value of HELLO_WORLD is: $(HELLO_WORLD)"
        displayName: 'Run Build Script'

  - job: Test
    displayName: 'Test Job'
    dependsOn: Build
    steps:
      - script: |
          echo Running tests...
          echo "Using HELLO_WORLD variable: $(HELLO_WORLD)"
        displayName: 'Run Tests'
