trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
      - script: |
          echo Building the project...
        displayName: 'Run Build Script'

  - job: Test
    displayName: 'Test Job'
    dependsOn: Build
    steps:
      - script: |
          echo Running tests...
        displayName: 'Run Tests'
