trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: HELLO_WORLD
    value: "default_value"

jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
      - script: |
          echo Building the project...
          echo $(HELLO_WORLD)
        displayName: 'Run Build Script'

  - job: Test
    displayName: 'Test Job'
    dependsOn: Build
    steps:
      - script: |
          echo Running tests...
        displayName: 'Run Tests'
